% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Jul-2020 19:55:40
%  MATLAB version: 9.7.0.1190202 (R2019b)
% -------------------------------------------------------------------
saveVarsMat = load('measurement_state_matrix_test.mat');

x = saveVarsMat.x; % <13x6012 double> too many elements

clear saveVarsMat;
